### ISSUE TITLE
2.3 breaks default "echo = false" argument

### ISSUE THREAD

**Issue by stklcode** [sheabunge/bookmarks-shortcode#1]
Commit https://github.com/sheabunge/bookmarks-shortcode/commit/89f88e2d51a6adf66d009cd0a2113da5dd225d0b in v2.3 breaks desired behavior, as the `echo=false` argument is no longer effective and thus the list is always echoed before the page content.

According to the WP spec the `$atts` argument of the shortcode might be a string. On one of my sites the argument actually is an empty string.

```php
$atts['echo'] = false;
```

on an empty string returns an empty string and `wp_list_bookmarks( '' );` obviously does not return a string.

**Test environment:**
* WP 4.9.8
* PHP 7.2
* Page content `<p>before</p><ul>[bookmarks]</ul><p>after</p>`

**Possible solution(s):**
I'd suggest to either revert this change and go back to `wp_parse_args()` or handle the 3 possible results (empty value, filled array, filled string) like this:
```php
function bookmarks_shortcode( $atts = array() ) {
	if ( empty( $atts ) ) {
		$atts = array( 'echo' => false );
	} elseif ( is_array( $atts ) ) {
		$atts['echo'] = false;
	} elseif ( is_string( $atts ) ) {
		$atts = 'echo=false&' . $atts;
	}
	return wp_list_bookmarks( $atts );
}
```

**Comment by sheabunge** [comment]
I wasn't aware that such variation was possible for the `$atts` parameter, so thanks for bringing this up. It looks like your fix is a great solution.
